name: Chocolatey build 

on: [create, push, pull_request]

env:
  NJOBS: 4

jobs:
  build:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    strategy:
      max-parallel: 10
      fail-fast: false
      matrix:
       include:
         - target_arch: x86_64
           compiler: gcc
           upload: 1
    env:
      TARGET_ARCH: ${{ matrix.target_arch }}
      COMPILER: ${{ matrix.compiler }}
      UPLOAD: ${{ matrix.upload }}
    steps:
    - uses: actions/checkout@v2
    - uses: msys2/setup-msys2@v2
      if: ${{ startsWith(github.ref, 'refs/tags/') }}
      with:
        update: true
        install: >-
          ccache
          clang
          cmake
          git
          make
          pkgconf
          python3
          mingw-w64-${{ matrix.target_arch }}-binutils
          mingw-w64-${{ matrix.target_arch }}-ccache
          mingw-w64-${{ matrix.target_arch }}-clang
          mingw-w64-${{ matrix.target_arch }}-cmake
          mingw-w64-${{ matrix.target_arch }}-ffmpeg
          mingw-w64-${{ matrix.target_arch }}-pkgconf
          mingw-w64-${{ matrix.target_arch }}-qt6
          mingw-w64-${{ matrix.target_arch }}-vlc
    - name: Release Build
      if: ${{ startsWith(github.ref, 'refs/tags/') }}
      run: ./ports/ci/windows-msys/build.sh
    - name: Release Deploy
      if: ${{ startsWith(github.ref, 'refs/tags/') }}
      run: ./ports/ci/windows-msys/deploy.sh
    - name: Release Upload Artifact 
      if: ${{ startsWith(github.ref, 'refs/tags/') && matrix.upload }}
      uses: actions/upload-artifact@v3
      with:
        name: installer
        path: |
          webcamoid-packages/windows-gcc-x86_64/*.exe
    - name: Create Release
      uses: softprops/action-gh-release@v1
      if: ${{ startsWith(github.ref, 'refs/tags/') && matrix.upload }}
      with:
        repository: ${{ github.repository }} 
        body: | 
          VERIFICATION 
          Verification is intended to assist the Chocolatey moderators and community
          in verifying that this package's contents are trustworthy.
          
          The binary installer was generated by the following workflow: 
          https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
          Please confirm that the md5sum sum of the installer binary using "Search logs" 
          or by looking at the very end of the "Release Deploy" step.
          
          Note: The original author also sells installer binaries under 
          https://webcamoid.github.io/ (please consider donating instead), 
          which should be completely equivalent, but might not match this hash, 
          because the build is not fully reproducible.
      env:
        GITHUB_TOKEN: ${{ secrets.UPLOAD_TOKEN }}
